### ISSUE TITLE
Should detect WMS, WFS, WCS formats correctly.

### ISSUE THREAD

**Issue by mwu2018** [magda-io/magda-minion-format#18]
**Describe the bug**
If a dataset has url of  https://portal.spatial.nsw.gov.au/server/services/Cadastre_History/MapServer/WMSServer, its format is  incorrectly detected as "ESRI MAPSERVER". It should be "WMS".

Technical Note:
1. If a dataset has url of  https://portal.spatial.nsw.gov.au/server/services/Cadastre_History/MapServer, its format is correctly detected as "ESRI MAPSERVER".
2. A dataset with url of https://portal.spatial.nsw.gov.au/server/services/Cadastre_History/MapServer/WFSServer should be detected as "WFS" format.
3. A dataset with url of https://portal.spatial.nsw.gov.au/server/services/Cadastre_History/MapServer/WCSServer should be detected as "WCS" format.

**To Reproduce**
1. Go to https://dev.nsw.digitaltwin.terria.io/#share=s-tF1QNV8Vw58HmVoZf4qRylwghYS
2. An error will occur if clicking on the item "Cadastre History". (The format is detected as "ESRI MAPSERVER").
3. No error will occur if clicking on the item "Cadastre History (WMS)". (The format is manually set as "WMS").

![image](https://user-images.githubusercontent.com/41275384/128459617-bf1791b5-02ef-4d33-851c-02bddb5e8e20.png)

**Comment by t83714** [comment]
@mwu2018 
For a map service, there might be served in the following ways formats (also see [here](https://github.com/magda-io/magda-minion-format/issues/8)):
- OGC WMS (e.g. GeoServer): It's response format is in XML
  - format minion will put as `WMS` format 
- ESRI Map Server: it's response format is in JSON
  - The pattern of the url you provided seem belongs to this category. i.e.:
  - https://portal.spatial.nsw.gov.au/server/services/Cadastre_History/MapServer
  - format minion will put as `ESRI MapServer` format 
- OGC WMS compatible service served over ESRI Map Server service (it has to be turned on via ESRI server config)
  - Its URL will look like this:
  - https://portal.spatial.nsw.gov.au/server/services/Cadastre_History/MapServer?request=GetCapabilities&service=WMS
  - format minion will put as `WMS` format 

It's also for matching the logic we had in [MagdaReference](https://github.com/TerriaJS/terriajs/blob/7c13c941fcce45f87c8dd597104154cb2429b7f8/lib/Models/Catalog/CatalogReferences/MagdaReference.ts#L101) --- in terriajs, they needs to be handled by differently (e.g. [WebMapServiceCatalogItem](https://github.com/TerriaJS/terriajs/blob/main/lib/Models/Catalog/Ows/WebMapServiceCatalogItem.ts) vs [ArcGisMapServerCatalogItem](https://github.com/TerriaJS/terriajs/blob/main/lib/Models/Catalog/Esri/ArcGisMapServerCatalogItem.ts))

Similar applies to `WFS` & `ESRI FeatureServer`.

Regarding `ESRI WCSServer`, can terriajs support it now?

**Comment by mwu2018** [comment]
Version `v0.0.58-terria.0` is being used for NSW DT where it correctly identifies https://portal.spatial.nsw.gov.au/server/services/Cadastre_History/MapServer as `ESRI MAPSERVER` because of https://github.com/magda-io/magda-minion-format/blob/v0.0.58-terria.0/synonyms.json that has
```
    "esri mapserver": [
        "esri rest",
        "ESRI ArcGIS",
        "map service",
        "esri map service"
    ],
```
`v0.0.58-terria.0`  incorrectly identifies https://portal.spatial.nsw.gov.au/server/services/Cadastre_History/MapServer/WMSServer as `ESRI MAPSERVER` but `v1.0.1` will correctly identify it as `WMS`. ~However `v1.0.1` may not identify https://portal.spatial.nsw.gov.au/server/services/Cadastre_History/MapServer as `ESRI MAPSERVER` as `v0.0.58-terria.0` does.~

It seems that `v1.0.1` will correctly detect both formats. Need to test it in NSW DT though.

**Comment by t83714** [comment]
@mwu2018  I think the test has been done and we can close this ticket, right?
