### ISSUE TITLE
Update synonyms.json file

### ISSUE THREAD

**Issue by mwu2018** [magda-io/magda-minion-format#3]
## Description
The current minion format does not create `dataset-format` correctly for esri dataset.

E.g. `dataset-format` aspect of esri item with id of `66895723791f4812b823d70637616bcb` from https://portal.spatial.nsw.gov.au/portal is

```
{
    "format": "SCENE",
    "confidenceLevel": 33
}
```

It should have been
```
{
    "format": "ESRI SCENESERVER",
    "confidenceLevel": 33
}
```

## Technical Notes

The current file is out-of-date for esri dataset. It needs to be synched to https://github.com/TerriaJS/magda/blob/terria/magda-minion-format/synonyms.json

**Comment by t83714** [comment]
We need to look at this when we have time to decide how to consolidate the format string differences among our projects.
See https://github.com/magda-io/magda-minion-format/pull/4

**Comment by t83714** [comment]
Superseded by #8
